# Generated by Django 5.1.3 on 2024-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
